version: '3.8'

services:
  backend:
    image: ghcr.io/aqiyoung/waf-backend:latest
    container_name: waf-backend
    ports:
      - "8009:8000"
    restart: unless-stopped
    networks:
      - waf-network

  frontend:
    image: ghcr.io/aqiyoung/waf-frontend:latest
    container_name: waf-frontend
    ports:
      - "89:80"
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - waf-network

networks:
  waf-network:
    driver: bridge
