version: '3.8'

services:
  backend:
    image: ghcr.io/aqiyoung/waf-backend:latest
    container_name: waf-backend
    network_mode: host
    environment:
      - PORT=8009
    restart: unless-stopped

  frontend:
    image: ghcr.io/aqiyoung/waf-frontend:latest
    container_name: waf-frontend
    network_mode: host
    environment:
      - PORT=89
    restart: unless-stopped
    depends_on:
      - backend
