version: '3.8'

services:
  backend:
    build: ./backend
    container_name: waf-backend
    network_mode: host
    environment:
      - PORT=8009
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: waf-frontend
    network_mode: host
    environment:
      - PORT=89
    restart: unless-stopped
    depends_on:
      - backend
